services:
  redis:
    image: redis:alpine
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/var/lib/redis
    restart: always
    pull_policy: always

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always
    pull_policy: always

volumes:
  redis-data: {}
  postgresql-data: {}
