name: Build Package

on:
  push:
    tags:
      - v*

permissions: write-all

jobs:
  build_package:
    name: Build Package
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.2.0

      # - name: Setup SSH Key
      #   uses: shimataro/ssh-key-action@v2.7.0
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa
      #     known_hosts: unnecessary
      #     config: |
      #       Host *
      #         StrictHostKeyChecking no
      #         UserKnownHostsFile=/dev/null
      #     if_key_exists: replace

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Version
        id: version
        shell: bash
        run: |
          VERSION=$(uvx dunamai from git --bump --no-metadata --style pep440)
          uv version $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # - name: Set tags
      #   id: version
      #   run: |
      #     if [[ $GITHUB_REF == refs/tags/* ]]; then
      #       VERSION=${GITHUB_REF#refs/tags/}
      #       echo "VERSION=${VERSION}" >> $GITHUB_ENV
      #       echo "version=${VERSION}" >> $GITHUB_OUTPUT
      #     else
      #       echo "VERSION=latest" >> $GITHUB_ENV
      #       echo "version=latest" >> $GITHUB_OUTPUT
      #     fi

      - name: Build Package
        run: |
          uv build

      # - name: Publish Package
      #   continue-on-error: true
      #   env:
      #     UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
      #   run: |
      #     uv publish

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        env:
          OUTPUT: CHANGELOG.md
        with:
          config: pyproject.toml
          args: --unreleased --tag ${{ steps.version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./dist/*
          name: ${{ github.event.repository.name }}-py${{ matrix.python-version }}
          if-no-files-found: ignore
          retention-days: 7
          compression-level: 6
          overwrite: true

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dist/*
