name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # manually trigger a workflow_dispatch event
  workflow_dispatch:

permissions: write-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: 'recursive'

      - name: Update Pre-Commit
        uses: browniebroke/pre-commit-autoupdate-action@main

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.10"
          pyproject-file: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        shell: bash
        run: |
          VERSION=$(uvx dunamai from git --bump --no-metadata --style pep440)
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $VERSION
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit any changes
        run: |
          git add -A
          git commit -m "Commit any changes before switching branches" || echo "No changes to commit"

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   id: pre-commit-autoupdate
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: chore/pre-commit-hooks
      #     title: 'chore: Update pre-commit hooks'
      #     body: Update versions of pre-commit hooks to latest version.

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master  # push to this branch
          branch: chore/pre-commit-hooks  # push from this branch
          title: "chore: Update pre-commit hooks"
          body: "Update versions of pre-commit hooks to latest version."
          commit-message: "chore: update pre-commit hooks"
          delete-branch: true

      - name: Auto Merge Pull Request
        if: steps.pre-commit-autoupdate.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge chore/pre-commit-hooks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
